### ISSUE TITLE
Add different levels of comparison to equality methods of Person class

### ISSUE THREAD

**Issue by Neurrone** [se-edu/addressbook-level2#122]
Add different levels of comparison to equality methods for Person. Sometimes we want to check if 2 persons contain same exact values (values of individual fields + privacy settings), and at other times, just to see if it is the same person (just field values). Also, Person.equals doesn't compare tags. Useful for simplifying testing.

**Comment by Neurrone** [comment]
Would like to work on this. What would be good names for the different levels of equality functions? The default equals (for strong equality) and weakEquals (not comparing privacy)?

**Comment by damithc** [comment]
`isSamePerson` (compare identity fields only), `hasSameData` (compare all fields)? `equals` can call `hasSameData` as usually equals means everything is the same.

**Comment by Neurrone** [comment]
Hm, existing code already relies on the current semantics of person.equals. E.g, this makes sense in the add command, as we don't need to consider the tags when detecting duplicate people. Looks like we need 3 levels?

| | compare address/email/phone/name? | compare tags? | compare privacy? |
| --- | --- | --- | --- |
| current person.equals | y | n | n |
| isSamePerson | y | y | n |
| hasSameData | y | y | y |

**Comment by damithc** [comment]
Yes, the current equals doesn't match the two levels I proposed. However, I think the correct thing to do is to make the 'add' method use `isSamePerson` instead of `equals` (because it's supposed to detect duplicate persons).  `isSamePerson` should only compare identity fields (_identity fields_ can be just `name` + `telephone` as those two are good enough to identify a duplicate person.)
@YijinL what do you think?

**Comment by YijinL** [comment]
I agree with the above post ^

| | compare minimum identifying set of data fields | compare all data (include tags and privacy) |
| --- | --- | --- |
| `isSamePerson` | Y | Y |
| `hasSameData` | Y | N |

We should pick one of those and use their logic under `equals`, if only because so many standard library classes use `equals`.
