### ISSUE TITLE
Addressbook::addTag() is not used

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level2#169]
addTag(), removeTag(), and containsTag() seem to be redundant.

**Comment by PierceAndy** [comment]
Should these redundant functions be removed, or should the respective commands be introduced into addressbook-level-2?

**Comment by PierceAndy** [comment]
addTag() and removeTag() appear to self-contained unused code, and can be safely removed.

However, removing containsTag() would result in poorer testing coverage, because containsTag() seems to be used in testing AddressBook#addPerson() to ensure that when adding a Person with Tags not already in the AddressBook's master list of Tags, these new tags are also added to the master list of Tags. [[For reference](https://github.com/se-edu/addressbook-level2/blob/master/test/java/seedu/addressbook/data/AddressBookTest.java#L94-L104)]

**Comment by damithc** [comment]
@PierceAndy did you add some comments to this issue and deleted them? I received email alerts about them but comments don't appear in this thread.

**Comment by PierceAndy** [comment]
@damithc I deleted those comments because I realized they were incorrect. Sorry about the alerts.
