### ISSUE TITLE
Potential documentation issue with developer guide -> setup

### ISSUE THREAD

**Issue by okkhoy** [se-edu/addressbook-level2#208]
OS: Ubuntu Linux 14.04
JDK: 1.8.0_144
IntelliJ: Community edition

To reproduce:
- Follow Step 11 for [setting up the project](https://github.com/nus-cs2103-AY1718S1/addressbook-level2/blob/master/doc/DeveloperGuide.md#setting-up).
- Run configuration:
![image](https://user-images.githubusercontent.com/1023494/29962464-ea330ade-8f35-11e7-8fd7-6c3fb592433e.png)
- Tests still fail:
![image](https://user-images.githubusercontent.com/1023494/29961541-8f64a304-8f32-11e7-962a-76ed75b221ca.png)
- Notice that when we select "Run all tests" a new configuration is created by IntelliJ
![image](https://user-images.githubusercontent.com/1023494/29961623-cd6fb148-8f32-11e7-8f92-491ce5887bb2.png)
- Selecting "All in test" configuration passes the tests:
![image](https://user-images.githubusercontent.com/1023494/29961664-ebb6416c-8f32-11e7-9278-0e9360651cf0.png)

![image](https://user-images.githubusercontent.com/1023494/29961687-fa3d24ee-8f32-11e7-95ac-8f5b92081278.png)

EDIT:
Inserted the correct image for run configuration

**Comment by damithc** [comment]
Does this happen even if you follow this step?
![image](https://user-images.githubusercontent.com/1673303/29962144-a59cc06e-8f34-11e7-8855-a6840d2099f1.png)

**Comment by okkhoy** [comment]
@damithc Yes. 
Before:
![image](https://user-images.githubusercontent.com/1023494/29962331-7cbd25ac-8f35-11e7-8fe3-9dee0b15fb20.png)
After:
![image](https://user-images.githubusercontent.com/1023494/29962364-9ae51738-8f35-11e7-9ce7-8b0bbb82532f.png)

**Comment by damithc** [comment]
I wonder if this is a better way to set the working directory for testing. @yamgent any ideas?

![image](https://user-images.githubusercontent.com/1673303/29962524-187ac1e8-8f36-11e7-8ea0-c9de83eb7b5f.png)

**Comment by yamgent** [comment]
> I wonder if this is a better way to set the working directory for testing. @yamgent any ideas?

I couldn't get that to work. The test cases still fail when I set the project as Test Sources Root (also tried Test Resources Root, didn't work either).

----

However, I found better alternative to our current solution in the dev guide. Our current solution only modifies the working directory for one configuration, so if a new configuration is spawned (which is what is happening with this issue when you press `Run All Test`), then the settings are different again.

The better solution would be to just modify the `Defaults\JUnit` configuration's working directory instead, so that new configurations created will inherit the values from the default configuration and use the correct working directory.

I tested it out and it works. Also, the `Defaults` here only affects the default settings for the __current__ project, not all projects that IntelliJ is handling, in case you are worried about that.

![default](https://user-images.githubusercontent.com/3168908/29972766-d87381aa-8f5f-11e7-8ce0-56d3bfb6da7a.png)

**Comment by damithc** [comment]
> However, I found better alternative to our current solution in the dev guide.

Nice. 👍 PR when you can.

**Comment by bokwoon95** [comment]
> The better solution would be to just modify the Defaults\JUnit configuration's working directory instead, so that new configurations created will inherit the values from the default configuration and use the correct working directory.

On MacOS, this results in a new test config being generated everytime a test is run.
<img width="141" alt="screen shot 2017-09-08 at 10 02 24 pm" src="https://user-images.githubusercontent.com/23723357/30215163-9573421e-94e1-11e7-832d-1e0b1fb33145.png">

However if I run the config directly with `Run>Run 'All in test'` from the menu bar rather than right-clicking the 'test' folder and selecting `Run 'All Tests'` it does not generate additional configs
<img width="345" alt="screen shot 2017-09-08 at 10 02 40 pm" src="https://user-images.githubusercontent.com/23723357/30215263-09a02724-94e2-11e7-8c86-77451f80c8ac.png">

**Comment by damithc** [comment]
More students are facing this issue. Shall we update the instructions? @yamgent @Zhiyuan-Amos  Might be applicable to level3 as well.

**Comment by Zhiyuan-Amos** [comment]
> On MacOS, this results in a new test config being generated everytime a test is run.

@yamgent this issue isn't resolved yet. It's ok that we don't resolve (cos nothing breaks), but it's still an issue. :/

**Comment by damithc** [comment]
> On MacOS, this results in a new test config being generated everytime a test is run.

I think it's the same in Windows. But now, it shouldn't matter because all test configurations inherit the default JUnit settings?

**Comment by Zhiyuan-Amos** [comment]
> I think it's the same in Windows. But now, it shouldn't matter because all test configurations inherit the default JUnit settings?

Yup it doesn't matter, just that it's still an unintended behaviour. I tried searching up for solutions but can't find any (I think I'm not that good at configuring stuffs haha). Shall I register this as an issue?

**Comment by damithc** [comment]
> Shall I record this as an issue?

What's the issue? My understanding is that it is no longer an issue because having multiple configurations doesn't affect the dev's work.

**Comment by yamgent** [comment]
> On MacOS, this results in a new test config being generated everytime a test is run.

This problem had always happened in all of my Java projects in IntelliJ in the past (and even till today). Regardless of whether you change any configuration settings, sometimes a new config will get generated anyway. I don't see a need for further action atm.
